### ISSUE TITLE
Characterbücher import mit den alternativen Charakterbögen funktioniert nur teilweise

### ISSUE THREAD

**Issue by Medugenus** [Graffini/bitd-foundry-de#2]
Bei einigen Klassen wie dem Emissär funktioiniert das automatische hinzufügen der Items nicht wenn die Klasse auf den Characterbogen verschoben wird.
Im Englischen funktioniert das.
Personen werden auch nicht hinzugefügt aber da die noch nicht übersetzt sind nehme ich an das ist normal.

Vielen Dank für deine tolle Arbeit. Es ist toll das Spiel mit der deutschen System-Matters ausgabe spielen zu können ohne den Sprach-Konflikt im VTT zu haben.

**Comment by Graffini** [comment]
Guter Hinweis, ist gefixt.
Ich schaue mal in einem separaten Issue, ob die NPCs nicht einfach wenigstens auf Englisch angezeigt werden können, auch wenn sie noch nicht übersetzt werden.
Danke für dein Feedback :) Freut mich, dass es genutzt wird.
